insert into Provinces (Name, Code)
values 
    ('Azua', 'AZ'),
    ('Bahoruco', 'BH'),
    ('Barahona', 'BR'),
    ('Dajabón', 'DJ'),
    ('Duarte', 'DU'),
    ('Elías Piña', 'EP'),
    ('El Seibo', 'ES'),
    ('Espaillat', 'ET'),
    ('Hato Mayor', 'HM'),
	('Hermanas Mirabal', 'HMI'),
	('Independencia', 'IN'),
    ('La Altagracia', 'LA'),
    ('La Romana', 'LR'),
    ('La Vega', 'LV'),
    ('María Trinidad Sánchez', 'MT'),
    ('Monseñor Nouel', 'MN'),
    ('Monte Cristi', 'MC'),
    ('Monte Plata', 'MT'),
    ('Pedernales', 'PE'),
    ('Peravia', 'PV'),
    ('Puerto Plata', 'PP'),
    ('Samaná', 'SA'),
    ('San Cristóbal', 'SC'),
    ('San José de Ocoa', 'SJO'),
    ('San Juan', 'SJ'),
    ('San Pedro de Macorís', 'SP'),
    ('Sánchez Ramírez', 'SR'),
    ('Santiago', 'SO'),
    ('Santiago Rodríguez', 'SRO'),
    ('Santo Domingo', 'SD'),
    ('Valverde', 'VA')